[project]
name = "news-aggregator"
version = "0.1.0"
description = "A simple python news aggregator project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.4",
]
